version: '3.9'
services:
  app:
    build:
      context: .
    container_name: nextjs-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: ['npm', 'run', 'dev']
    restart: unless-stopped
